language: java

jdk:
  - oraclejdk7

install: ant get-ivy

script: ant test

notifications:
  email:
    recipients:
      - secure: L51bkmo1i3iFOzZAL7JOXxZu0jCEuQ8UrPQChzZJUaY+obHQSi+u4AcOVw3YjZeoAm2s7QuktI9kKi+ehwhQd82qVezT/SRPb1ZBecAydbdkC+KvEc2qdMV7qqHuLJ6biW/dQn5UIa8prI96pV2GuEusO4FVSiz4XXCdgpxS6T4=
    on_success: always

